import { Roboto } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "../../assets/style/main.css";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Pratik's Porfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={roboto.className}
      >
       {children}
      </body>
    </html>
  );
}
